name: Test Setup Godot Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-godot-setup-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Godot
        uses: ./
        with:
          version: '4.4.1-stable'
          platform: 'linux.x86_64'
      - name: Check Godot version
        run: |
          $GODOT4 --version
  test-godot-setup-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Godot
        uses: ./
        with:
          version: '4.4.1-stable'
          platform: 'macos.universal'
      - name: Check Godot version
        run: |
          $GODOT4 --version
  test-godot-setup-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Godot
        uses: ./
        with:
          version: '4.4.1-stable'
          platform: 'win64.exe'
      - name: Check Godot version
        shell: pwsh
        run: |
          & $env:GODOT4 --version
