name: Test Setup Godot Action

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test-godot-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Godot
        uses: ./
        with:
          version: '4.4.1-stable'
          platform: 'linux.x86_64'
      - name: Check Godot version
        run: |
          GODOT_BIN_PATH --version
